services:
  app:
    build: .
    image: temis-mems-lab:latest
    container_name: temis-mems-lab
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs
      - ./config:/app/config
      - ./setup:/app/setup
    # This allows the container to resolve 'host.docker.internal' on Windows/Mac
    extra_hosts:
      - "host.docker.internal:host-gateway"
