import socket
import time
import os
from zeroconf import Zeroconf, ServiceBrowser, ServiceListener

class InstrumentListener(ServiceListener):
    def __init__(self, targets):
        self.targets = {t.lower(): t for t in targets}
        self.found = {}

    def add_service(self, zc, type_, name):
        info = zc.get_service_info(type_, name)
        if info:
            host_part = info.server.lower().split('.')[0]
            addresses = info.parsed_addresses()
            if not addresses: return
            if host_part in self.targets:
                self.found[self.targets[host_part]] = addresses[0]
                print(f"  [+] Found {self.targets[host_part]} at {addresses[0]}")
            elif "zna" in host_part or "zva" in host_part:
                self.found["ZNA67-101810"] = addresses[0]
                print(f"  [+] Found VNA ({host_part}) at {addresses[0]}")

    def update_service(self, zc, type_, name):
        self.add_service(zc, type_, name)

    def remove_service(self, zc, type_, name):
        pass

def resolve_all():
    targets = [
        "ZNA67-101810",
        "A-33521B-00526",
        "rssmb100a179766",
        "DPO5054-C011738"
    ]
    
    print("Searching for instruments on the network...")
    found_ips = {}
    
    # 1. Try standard DNS/WINS first
    for target in targets:
        try:
            ip = socket.gethostbyname(target)
            found_ips[target] = ip
            print(f"  [+] Resolved {target} to {ip} via DNS")
        except socket.gaierror:
            pass

    # 2. Try mDNS for the remaining
    remaining = [t for t in targets if t not in found_ips]
    if remaining:
        zeroconf = Zeroconf()
        listener = InstrumentListener(remaining)
        services = ["_vxi-11._tcp.local.", "_hislip._tcp.local.", "_lxi._tcp.local."]
        browser = ServiceBrowser(zeroconf, services, listener)
        
        time.sleep(3) # Give it time to discover
        zeroconf.close()
        found_ips.update(listener.found)

    # 3. Save to .env
    with open(".env", "w") as f:
        f.write("# Auto-generated by resolve_ips.py\n")
        f.write(f"VNA_IP={found_ips.get('ZNA67-101810', 'ZNA67-101810')}\n")
        f.write(f"SIG_GEN_IP={found_ips.get('A-33521B-00526', 'A-33521B-00526')}\n")
        f.write(f"RF_GEN_IP={found_ips.get('rssmb100a179766', 'rssmb100a179766')}\n")
        f.write(f"OSC_IP={found_ips.get('DPO5054-C011738', 'DPO5054-C011738')}\n")
        f.write(f"POWERMETER_IP=169.254.64.175\n") # Powermeter is typically static

    print("\n[DONE] IP addresses saved to .env")
    print("You can now run 'docker compose up'!")

if __name__ == "__main__":
    resolve_all()
